### ISSUE TITLE
Docker logs give error - FPM instance seems to already listen on /php/run/php-fpm.sock 

### ISSUE THREAD

**Issue by StefanVietze** [benyanke/docker-nextcloud#7]
Hi @benyanke,

I have migrated to your repo and use your images now but the problem described at https://github.com/Wonderfall/docker-nextcloud/issues/12 still persists.

Nextcloud seems to be syncing again but some files won't be synced to the server. Container logs of the nextcloud container still gives:
```
ERROR: FPM initialization failed
ERROR: An another FPM instance seems to already listen on /php/run/php-fpm.sock
```
every second.

I am using nextcloud behind JrCs LetsEncrypt nginx proxy:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

I am using following `docker-compose.yml`:
```
version: '2'

volumes:
  db-data:
  data:
  config:
  apps:
  nginx-log:
  redis:

services:
  nextcloud-db:
    restart: always
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<mysql_root_pwd>
      - MYSQL_DATABASE=<db_name>
      - MYSQL_USER=<db_user>
      - MYSQL_PASSWORD=<mysql_pwd>

  nextcloud:
    restart: always
    image: benyanke/nextcloud:latest
    environment:
      - DOMAIN=<domain_name>
      - UID=991
      - GID=991
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=512M
      - OPCACHE_MEM_SIZE=512
      - REDIS_MAX_MEMORY=64mb
      - CRON_PERIOD=10m
      - TZ=Europe/Vienna
      - ADMIN_USER=<admin_user>
      - ADMIN_PASSWORD=<admin_pwd>
      - DB_TYPE=mysql
      - DB_NAME=<db_name>
      - DB_USER=<db_user>
      - DB_PASSWORD=<mysql_pwd>
      - DB_HOST=nextcloud-db
      - VIRTUAL_PORT=9000
      - VIRTUAL_HOST=<domain_name>
      - LETSENCRYPT_HOST=<domain_name>
      - LETSENCRYPT_EMAIL=<my_mail_address>
    depends_on:
      - nextcloud-db
    volumes:
      - data:/data
      - config:/config
      - apps:/apps2
    links:
      - nextcloud-db:nextcloud-db
      - redis:redis

  redis:
    restart: always   
    image: redis:alpine   
    container_name: redis   
    volumes:     
      - redis:/data

networks:
    default:
       external:
         name: webproxy

```

Do you have any idea?
